server:
  port: 8081

spring:
  mvc:
    path_match:
      matching-strategy: ant_path_matcher

  datasource:
    master:
      hikari:
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${DB_HOST_MASTER}:3306/${DB_NAME}
    slave:
      hikari:
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${DB_HOST_SLAVE1}:3306/${DB_NAME}
    slave2:
      hikari:
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${DB_HOST_SLAVE2}:3306/${DB_NAME}
  jpa:
    # local
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #    RDS
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: ${MONGO_URI}

  rabbitmq:
    dynamic: true
    listner:
      simple:
        retry :
          enabled : true
          initial-interval: 3s #최초 재시도 간격시간
          max-attemps: 3 # 재시도 최대 횟수
          max-interval: 10s # 최대 재시도 간격 시간
          multiplier: 2 #initial-interval의 계수
    host: ${RMQ_HOST}
    port: 5672
    username: ${RMQ_USER}
    password: ${RMQ_PASSWORD}
