server:
  port: 8081
spring:
  mvc:
    path_match:
      matching-strategy: ant_path_matcher

  datasource:
    master:
      hikari:
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    slave:
      hikari:
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    slave2:
      hikari:
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
  jpa:
    # local
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #    RDS
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

rabbitmq:
  host: ${RMQ_HOST}
  port: 5672
  username: ${RMQ_USER}
  password: ${RMQ_PASSWORD}